language: python
before_install:
    - wget -q http://repo.continuum.io/miniconda/Miniconda-3.6.0-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p /home/travis/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes --quiet conda
install:
    - conda create -n testenv --yes pip python=3.6
    - source activate testenv
    - conda install --yes --quiet numpy scipy matplotlib scikit-learn pandas
    - pip install -q flake8
    - python setup.py install
    - mkdir kits
    - cd kits
    - git clone https://github.com/ramp-kits/boston_housing.git
    - cd ..
script:
    - nosetests rampwf/tests
    - cd kits/boston_housing
    - test_submission
notifications:
  email: true
