build: false

environment:
  matrix:
    #- PYTHON: "C:\\Miniconda-x64"
    #  PYTHON_VERSION_ENV: "2.7"
    #  PYTHON_VERSION: "2.7.x"
    #  PYTHON_ARCH: "64"

    - PYTHON: "C:\\Miniconda3-x64"
      PYTHON_VERSION_ENV: "3.5"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Miniconda3-x64"
      PYTHON_VERSION_ENV: "3.6"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

install:
  # Prepend miniconda installed Python to the PATH of this build
  # Add Library/bin directory to fix issue
  # https://github.com/conda/conda/issues/1753
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\Library\\bin;%PATH%"
  - conda create -n testenv --yes ipykernel pip python=%PYTHON_VERSION_ENV%
  - activate testenv
  - pip install -r requirements.txt
  - pip install -r testing-requirements.txt
  - pip install -e .

test_script:
  - pytest -s -v --pyargs rampwf --cov-report term-missing --cov=rampwf
